services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - ./config/:/config/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_CONFIG=./config
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true
